In [9]:
import sqlite3

    
def connect_database():
    try:
        
        con=sqlite3.connect("library.db")
        cur=con.cursor()
        cur.execute('''
                create table if not exists books
                ( book_id integer primary key,
                  author text not null,
                  title text not null,
                  quantity integer not null)
                    ''')
        return con,cur
    except sqlite3.Error as e:
        print("Error creating connection:", e)
        return None, None


def close_connection(con, cur):
    if cur:
        cur.close()
    if con:
        con.close()
def add_book():
    con,cur=connect_database()
    try:
        
        author=input("enter the author of the book:")
        title=input("enter the title of the book:")
        quantity=int(input("enter the quantity:"))
        cur.execute('''insert into books (author,title,quantity) values(?,?,?)''',(author,title,quantity))
        con.commit()
        print("book added successfully")
    except sqlite3.Error as error:
        print("error:",error)
    finally:
        close_connection(con, cur)
def update_book():
    con,cur=connect_database()
    try:
        book_id=input("enter the id of the book: ")
        new_author=input("enter the new author:")
        new_title=input("enter the new title:")
        new_quantity=int(input("enter the new quantity:"))
        cur.execute('''update books set author=?,
                        set title=?,
                        set quantity=?
                        where book_id=book_id''',(new_author,new_title,new_quantity))
    except sqlite3.Error as error:
        print("error",error)
    finally:
        close_connection(con, cur)
def search_bookbyid():
    con,cur=connect_database()
    try:
        book_id=input("enter the book id to search:")
        cur.execute('''select * from books where book_id=?''',(book_id,))
        book=cur.fetchone()
        if book:
            print("bookid:",book[0])
            print("book author:",book[1])
            print("book title:",book[2])
            print("book quantity:",book[3])
        else:
            print("book not found")
    except sqlite3.Error as error:
        print("error",error)
    finally:
        close_connection(con, cur)

def search_bookbyauthor():
    con,cur=connect_database()
    try:
        author=input("enter the author name:")
        cur.execute('''select *from books where author like ?''',('%'+author+'%',))
        book1=cur.fetchall()
        if book1:
            for book in book1:
                print("book id:",book[0])
                print("book author:",book[1])
                print("book title:",book[2])
                print("book quantity:",book[3])
        else:
            print("not found")
    except sqlite3.Error as error:
        print("error",error)
    finally:
        close_connection(con, cur)
def delete_book():
    con,cur=connect_database()
    try:
        book_id=int(input("enter the book id to delete book:"))
        cur.execute('''select * from books where book_id=?''',(book_id,))
        book=cur.fetchone()
        if book:
            cur.execute('''delete from books where book_id=?''',(book_id,))
            con.commit()
            print("book deleted successfully")
        else:
            print("book not found")
    except sqlite3.Error as error:
        print("error",error)
    finally:
        close_connection(con, cur)
def display():
    con,cur=connect_database()
    try:
        cur.execute('''select *from books''')
        bookfinal=cur.fetchall()
        if bookfinal:
            
            for bookss in bookfinal:
                print(bookss)
        else:
            print("No books present")
            
    except sqlite3.Error as error:
        print("error",error)
    finally:
        close_connection(con, cur)


while True:
    print("Menu for Library management")
    print("1.add book\n")
    print("2.update book\n")
    print("3.search book by id\n")
    print("4.search book by author\n")
    print("5.delete book\n")
    print("6.display\n")
    choice=int(input("enter the choice: "))
    if choice==1:
        add_book()
    elif choice==2:
        update_book()
    elif choice==3:
        search_bookbyid()
    elif choice==4:
        search_bookbyauthor()
    elif choice==5:
        delete_book()
    elif choice==6:
        display()
    else:
        print("wrong")
        break

Menu for Library management
1.add book

2.update book

3.search book by id

4.search book by author

5.delete book

6.display

enter the choice: 6
(1, 'J.K. Rowling', 'Harry Potter', 3)
(2, 'R.L.Stine', 'Goosebumps', 4)
(3, 'Enid Blyton', 'Noddy', 7)
(4, 'Dan Brown', 'Robert Langdon', 6)
Menu for Library management
1.add book

2.update book

3.search book by id

4.search book by author

5.delete book

6.display

enter the choice: 1
enter the author of the book:C.S.Lewis
enter the title of the book:The Chronicles Of Narnia
enter the quantity:5
book added successfully
Menu for Library management
1.add book

2.update book

3.search book by id

4.search book by author

5.delete book

6.display

enter the choice: 1
enter the author of the book:T.Hardy
enter the title of the book:A Pair Of Blue Eyes
enter the quantity:5
book added successfully
Menu for Library management
1.add book

2.update book

3.search book by id

4.search book by author

5.delete book

6.display

enter the choice: 1
enter the author of the book:J.Austen
enter the title of the book:Pride and Prejudice
enter the quantity:6
book added successfully
Menu for Library management
1.add book

2.update book

3.search book by id

4.search book by author

5.delete book

6.display

enter the choice: 3
enter the book id to search:2
bookid: 2
book author: R.L.Stine
book title: Goosebumps
book quantity: 4
Menu for Library management
1.add book

2.update book

3.search book by id

4.search book by author

5.delete book

6.display

enter the choice: 4
enter the author name:T.Hardy
book id: 6
book author: T.Hardy
book title: A Pair Of Blue Eyes
book quantity: 5
Menu for Library management
1.add book

2.update book

3.search book by id

4.search book by author

5.delete book

6.display

enter the choice: 2
enter the id of the book: 3
enter the new author:H.H.Munro
enter the new title:The Chronicles Of Clovis
enter the new quantity:6
error near "set": syntax error
Menu for Library management
1.add book

2.update book

3.search book by id

4.search book by author

5.delete book

6.display

enter the choice: 6
(1, 'J.K. Rowling', 'Harry Potter', 3)
(2, 'R.L.Stine', 'Goosebumps', 4)
(3, 'Enid Blyton', 'Noddy', 7)
(4, 'Dan Brown', 'Robert Langdon', 6)
(5, 'C.S.Lewis', 'The Chronicles Of Narnia', 5)
(6, 'T.Hardy', 'A Pair Of Blue Eyes', 5)
(7, 'J.Austen', 'Pride and Prejudice', 6)
Menu for Library management
1.add book

2.update book

3.search book by id

4.search book by author

5.delete book

6.display

enter the choice: 1
enter the author of the book:Colette
enter the title of the book:Cheri
enter the quantity:6
book added successfully
Menu for Library management
1.add book

2.update book

3.search book by id

4.search book by author

5.delete book

6.display

enter the choice: 1
enter the author of the book:Ali Smith
enter the title of the book:Seasonal quartet
enter the quantity:2
book added successfully
Menu for Library management
1.add book

2.update book

3.search book by id

4.search book by author

5.delete book

6.display

enter the choice: 6
(1, 'J.K. Rowling', 'Harry Potter', 3)
(2, 'R.L.Stine', 'Goosebumps', 4)
(3, 'Enid Blyton', 'Noddy', 7)
(4, 'Dan Brown', 'Robert Langdon', 6)
(5, 'C.S.Lewis', 'The Chronicles Of Narnia', 5)
(6, 'T.Hardy', 'A Pair Of Blue Eyes', 5)
(7, 'J.Austen', 'Pride and Prejudice', 6)
(8, 'Colette', 'Cheri', 6)
(9, 'Ali Smith', 'Seasonal quartet', 2)
Menu for Library management
1.add book

2.update book

3.search book by id

4.search book by author

5.delete book

6.display

enter the choice: 1
enter the author of the book:Lois Lowry
enter the title of the book:The king of Danish
enter the quantity:8
book added successfully
Menu for Library management
1.add book

2.update book

3.search book by id

4.search book by author

5.delete book

6.display

enter the choice: 6
(1, 'J.K. Rowling', 'Harry Potter', 3)
(2, 'R.L.Stine', 'Goosebumps', 4)
(3, 'Enid Blyton', 'Noddy', 7)
(4, 'Dan Brown', 'Robert Langdon', 6)
(5, 'C.S.Lewis', 'The Chronicles Of Narnia', 5)
(6, 'T.Hardy', 'A Pair Of Blue Eyes', 5)
(7, 'J.Austen', 'Pride and Prejudice', 6)
(8, 'Colette', 'Cheri', 6)
(9, 'Ali Smith', 'Seasonal quartet', 2)
(10, 'Lois Lowry', 'The king of Danish', 8)
Menu for Library management
1.add book

2.update book

3.search book by id

4.search book by author

5.delete book

6.display

enter the choice: 8
wrong